### ISSUE TITLE
Authconfig update

### ISSUE THREAD

**Issue by gonrada** [ASCIIDuck/asciiduck-sssd#2]
Would it be possible to have the module enable sssd via authconfig?
"authconfig --enablesssd --enablesssdauth --update"

**Comment by ASCIIDuck** [comment]
It would certainly be possible, I am hesitant to have it do so though because I think touching the pam and nsswitch config should be the task of another module (for example, maybe https://forge.puppetlabs.com/yguenane/authconfig). Feature creep is a particular concern with puppet modules as only one module can really manage a given resource. I could have a flag that controlled whether or not this module attempted to do the authconfig but it seems a lot cleaner to me to just use a module dedicated to that purpose.

**Comment by gonrada** [comment]
Thanks for the reply. I had looked at the authconfig module but I just decided it was simpler to use an exec statement.
    exec { "authconfig_enablesssd":
        command => 'authconfig --enablesssd --enablesssdauth --update',
        path => "/usr/sbin:/bin:/usr/bin",
        onlyif => "test `grep USESSSDAUTH /etc/sysconfig/authconfig | cut -d= -f 2` != 'yes'",
    }
I'm not the only person who will have to manage our puppet stack and I try my best to keep as few moving parts as possible.
